name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Set up MemKernel as a module (M-OUT) with specified name
      run: |
        curl -LSs "https://raw.githubusercontent.com/kuronami69/MemKernel/main/kernel/setup.sh" | bash -s M

    - name: Install cross-compiler for ARM
      run: |
        sudo apt-get update
        if [[ "${{ inputs.arch }}" == "arm64" ]]; then
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          echo "Compiler version: $(gcc-aarch64-linux-gnu --version | head -n 1)"
          echo "compiler_version=aarch64-linux-gnu" >> $GITHUB_ENV
        elif [[ "${{ inputs.arch }}" == "arm32" ]]; then
          sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
          echo "Compiler version: $(gcc-arm-linux-gnueabi --version | head -n 1)"
          echo "compiler_version=arm-linux-gnueabi" >> $GITHUB_ENV
        else
          echo "Unsupported architecture"
          exit 1
        fi

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: Loganysl
      with:
        arch: arm64
        compiler: ${{ env.compiler_version }}
        defconfig: gki_defconfig
        image: Image.gz-dtb

    - name: Upload Kernel and Module
      uses: actions/upload-artifact@v4
      with:
        name: module
        path: |
          ${{ steps.build.outputs.outfile }}
          ./out/drivers/memkernel/memkernel.ko
