name: Build Kernel

on:
  workflow_dispatch:
  schedule:
    # Runs every Saturday at 00:00 UTC
    - cron: "0 0 * * 6"
  push:
    branches:
      - HEAD
  pull_request:
    branches:
      - HEAD

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_DEFCONFIG: "vayu_defconfig"
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- O=out"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: "true"
        fetch-depth: 100

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi \
          aria2 \
          binutils \
          make \
          python3 \
          libssl-dev \
          build-essential \
          bc \
          bison \
          flex \
          unzip \
          ca-certificates \
          xz-utils \
          mkbootimg \
          cpio \
          device-tree-compiler \
          git \
          git-lfs
        # Set up custom Clang
        aria2c -j$(nproc --all) $(curl -fsSL https://github.com/ZyCromerZ/Clang/raw/main/Clang-main-link.txt)
        mkdir zyc-clang
        tar -xzvf Clang-*.tar.gz -C zyc-clang >> /dev/null
        #mem module
        curl -LSs "https://raw.githubusercontent.com/kuronami69/MemKernel/main/kernel/setup.sh" | bash -s M anrwt
        
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC+3 date +%s)" >> $GITHUB_OUTPUT
    - name: Upload mem module
      uses: actions/upload-artifact@v4
      with:
        name: memodule
        path: |
          ${{ steps.build.outputs.outfile }}
          ./out/drivers/memkernel/memkernel.ko
